# Generated by Django 3.2.4 on 2021-06-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brief_description', models.CharField(max_length=200)),
                ('Education', models.TextField()),
                ('Experience', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('Projects', models.CharField(max_length=200)),
                ('Summary', models.TextField(default='this is awesome!')),
            ],
        ),
    ]
