# Generated by Django 3.2.4 on 2021-06-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resume_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='IsActive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
